name: "The Lewis'"
favicon: null
layout_spectrum: 0.69350970024243
typography_spectrum: 0.0865485139656812
title: "Kristy & Darin's Life"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.706376176327467
  lightness: 0.8379330311436206
  saturation: 0.22238784818910062
  rhythmicContrast: 0.8366263876669109
purpose: []
